{
    "openapi": "3.0.0",
    "info":{
    "title": "Node Swagger",
    
    "description": "Documentação Api Cardápio",
    "contact":{
        "email": "esmirnamneris@gmail.com"
    },
    "version": "1.0.00"
},

"servers":[
    {
        "url": "http://localhost:3000",
        "description": "API"
    }
],

"paths":{
    "/adicional": {
        "post": {
            "summary": "Cadastrar Adicional",
            "description": "Rota para cadastrar um novo adicional",
            "tags": ["Adicionais"],
            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Adicional"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 1,
                                    "nome":"Salada de Alface",
                                    "descrição" : "Alface, Cebola, Tomate e Vinagre",
                                    "preço": 8,
                                    "vegetariano": true
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "400":{
                    "description": "Bad Request"
                },
                "404":{
                    "description": "Not found"
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },
    "/adicionais": {
        "get":{
           "description": "Buscar adicionais cadastrados",
           "summary": "Buscar adicionais cadastrados",
           "tags": ["Adicionais"],
           "responses": {
            "404": {
                "description": "Not Found!"
            },
            "200":{
                "description": "ok",
                "content": {
                    "application/json": {
                        "scema": {
                            "type": "object",
                            "intens": {
                                "$ref": "#/components/schemas/Adicional"
                            }
                        }
                    }
                }
            },
            "500":{
                "description": "Internal Server Error"
            }
        }
        
        }
    },
    "/adicional/{id}": {
        "get": {
            "description": "Buscar adicional cadastrado pelo id",
            "summary": "Buscar adicional cadastrado pelo id",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id do adicional para busca",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "put": {
            "description": "Alterar adicional cadastrado pelo id",
            "summary": "Alterar adicional cadastrado pelo id",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id do adicional que deseja atualizar",
                    "required": true
                }
            ],

            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Adicional"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 1,
                                    "nome":"feijoada",
                                    "descrição" : "Arroz, farofa, couve, feijão separado & laranja, carne seca, costela suina, calabresa e paio",
                                    "preço": 24,
                                    "vegetariano": false
                                }
                            }
                        }
                    }
                }
            },

            "responses": {
                "404": {
                    "description": "Not Found"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "delete": {
            "description": "Excluir adicional cadastrado pelo id",
            "summary": "Excluir adicional cadastrado pelo id",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id do adicional que deseja excluir",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },
    "/adicional/codigo/{codigo}": {
        "get": {
            "description": "Buscar adicional cadastrado pelo codigo",
            "summary": "Buscar adicional cadastrado pelo codigo",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "Codigo do adicional para busca",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "put": {
            "description": "Alterar adicional cadastrado pelo codigo",
            "summary": "Alterar adicional cadastrado pelo codigo",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "codigo do adicional que deseja atualizar",
                    "required": true
                }
            ],

            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Adicional"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 1,
                                    "nome":"feijoada",
                                    "descrição" : "Arroz, farofa, couve, feijão separado & laranja, carne seca, costela suina, calabresa e paio",
                                    "preço": 24,
                                    "vegetariano": false
                                }
                            }
                        }
                    }
                }
            },

            "responses": {
                "404": {
                    "description": "Not Found"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "delete": {
            "description": "Excluir adicional cadastrado pelo codigo",
            "summary": "Excluir adicional cadastrado pelo codigo",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "codigo do adicional que deseja excluir",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },






    "/bebida": {
        "post": {
            "summary": "Cadastrar Bebida",
            "description": "Rota para cadastrar uma nova Bebida",
            "tags": ["Bebidas"],
            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Bebida"
                        },
                        "examples": {
                            "Bebida": {
                                "value": {
                                    "codigo": 2,
                                    "nome":"Suco natural de limão",
                                    "descrição" : "Polpa de limao, agua, azucar, contém, 300 ml",
                                    "preço": 6,
                                    "álcool": false
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Bebida"
                                }
                            }
                        }
                    }
                },
                "400":{
                    "description": "Bad Request"
                },
                "404":{
                    "description": "Not found"
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },
    
    "/bebidas": {
        "get":{
           "description": "Buscar Bebidas cadastradas",
           "summary": "Buscar Bebidas cadastradas",
           "tags": ["Bebidas"],
           "responses": {
            "404": {
                "description": "Not Found!"
            },
            "200":{
                "description": "ok",
                "content": {
                    "application/json": {
                        "scema": {
                            "type": "object",
                            "intens": {
                                "$ref": "#/components/schemas/Bebida"
                            }
                        }
                    }
                }
            },
            "500":{
                "description": "Internal Server Error"
            }
        }
        
        }
    },
    "/bebida/{id}": {
        "get": {
            "description": "Buscar Bebida cadastrada pelo id",
            "summary": "Buscar Bebida cadastrada pelo id",
            "tags": ["Bebidas"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id da bebida para busca",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Bebida"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "put": {
            "description": "Alterar Bebida cadastrada pelo id",
            "summary": "Alterar Bebida cadastrada pelo id",
            "tags": ["Bebidas"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id da bebida que deseja atualizar",
                    "required": true
                }
            ],

            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Bebida"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 2,
                                    "nome":"Suco natural de limão",
                                    "descrição" : "Polpa de limao, agua, azucar, contém, 300 ml",
                                    "preço": 6,
                                    "álcool": false
                                }
                            }
                        }
                    }
                }
            },

            "responses": {
                "404": {
                    "description": "Not Found"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Bebida"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "delete": {
            "description": "Excluir Bebida cadastrada pelo id",
            "summary": "Excluir Bebida cadastrada pelo id",
            "tags": ["Bebidas"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id da bebida que deseja excluir",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Bebida"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },
    "/bebida/codigo/{codigo}": {
        "get": {
            "description": "Buscar Bebida cadastrada pelo codigo",
            "summary": "Buscar Bebida cadastrada pelo codigo",
            "tags": ["Bebidas"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "Codigo da bebida para busca",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Bebida"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "put": {
            "description": "Alterar Bebida cadastrada pelo codigo",
            "summary": "Alterar Bebida cadastrada pelo codigo",
            "tags": ["Bebidas"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "codigo da bebida que deseja atualizar",
                    "required": true
                }
            ],

            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Bebida"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 2,
                                    "nome":"Suco natural de limão",
                                    "descrição" : "Polpa de limao, agua, azucar, contém, 300 ml",
                                    "preço": 6,
                                    "álcool": false
                                }
                            }
                        }
                    }
                }
            },

            "responses": {
                "404": {
                    "description": "Not Found"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "delete": {
            "description": "Excluir bebida cadastrada pelo codigo",
            "summary": "Excluir bebida cadastrada pelo codigo",
            "tags": ["Bebidas"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "codigo doa bebida que deseja excluir",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Bebida"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },

    




    "/prato": {
        "post": {
            "summary": "Cadastrar Adicional",
            "description": "Rota para cadastrar um novo adicional",
            "tags": ["Adicionais"],
            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Adicional"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 1,
                                    "nome":"Salada de Alface",
                                    "descrição" : "Alface, Cebola, Tomate e Vinagre",
                                    "preço": 8,
                                    "vegetariano": true
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "400":{
                    "description": "Bad Request"
                },
                "404":{
                    "description": "Not found"
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },
    "/adicionais": {
        "get":{
           "description": "Buscar adicionais cadastrados",
           "summary": "Buscar adicionais cadastrados",
           "tags": ["Adicionais"],
           "responses": {
            "404": {
                "description": "Not Found!"
            },
            "200":{
                "description": "ok",
                "content": {
                    "application/json": {
                        "scema": {
                            "type": "object",
                            "intens": {
                                "$ref": "#/components/schemas/Adicional"
                            }
                        }
                    }
                }
            },
            "500":{
                "description": "Internal Server Error"
            }
        }
        
        }
    },
    "/adicional/{id}": {
        "get": {
            "description": "Buscar adicional cadastrado pelo id",
            "summary": "Buscar adicional cadastrado pelo id",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id do adicional para busca",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "put": {
            "description": "Alterar adicional cadastrado pelo id",
            "summary": "Alterar adicional cadastrado pelo id",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id do adicional que deseja atualizar",
                    "required": true
                }
            ],

            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Adicional"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 1,
                                    "nome":"feijoada",
                                    "descrição" : "Arroz, farofa, couve, feijão separado & laranja, carne seca, costela suina, calabresa e paio",
                                    "preço": 24,
                                    "vegetariano": false
                                }
                            }
                        }
                    }
                }
            },

            "responses": {
                "404": {
                    "description": "Not Found"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "delete": {
            "description": "Excluir adicional cadastrado pelo id",
            "summary": "Excluir adicional cadastrado pelo id",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "Id do adicional que deseja excluir",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },
    "/adicional/codigo/{codigo}": {
        "get": {
            "description": "Buscar adicional cadastrado pelo codigo",
            "summary": "Buscar adicional cadastrado pelo codigo",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "Codigo do adicional para busca",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "put": {
            "description": "Alterar adicional cadastrado pelo codigo",
            "summary": "Alterar adicional cadastrado pelo codigo",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "codigo do adicional que deseja atualizar",
                    "required": true
                }
            ],

            "requestBody": {
                "content": {
                    "application/json":{
                        "schema":{
                          "$ref": "#/components/schemas/Adicional"
                        },
                        "examples": {
                            "Adicional": {
                                "value": {
                                    "codigo": 1,
                                    "nome":"feijoada",
                                    "descrição" : "Arroz, farofa, couve, feijão separado & laranja, carne seca, costela suina, calabresa e paio",
                                    "preço": 24,
                                    "vegetariano": false
                                }
                            }
                        }
                    }
                }
            },

            "responses": {
                "404": {
                    "description": "Not Found"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        },
        "delete": {
            "description": "Excluir adicional cadastrado pelo codigo",
            "summary": "Excluir adicional cadastrado pelo codigo",
            "tags": ["Adicionais"],
            "parameters": [
                {
                    "name": "codigo",
                    "in": "path",
                    "description": "codigo do adicional que deseja excluir",
                    "required": true
                }
            ],
            
            "responses": {
                "404": {
                    "description": "Not Found!"
                },
                "200":{
                    "description": "ok",
                    "content": {
                        "application/json": {
                            "scema": {
                                "type": "object",
                                "intens": {
                                    "$ref": "#/components/schemas/Adicional"
                                }
                            }
                        }
                    }
                },
                "500":{
                    "description": "Internal Server Error"
                }
            }
        }
    },






    


},

"components":{
    "schemas": {
        "Adicional":{
                "type": "object",
                "properties": {
                    "codigo":{
                        "type": "number"
                    },

                    "nome":{
                        "type": "string"
                    },
                    "descrição": {
                        "type": "String"
                        
                    },

                   "preço": {
                        "type": "number"
                    },

                    "vegetariano": {
                        "type": "boolean"
                
                    }
                }
            }
        }
    }
}